[package]
name = "tensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
proptest = "1.2.0"
proptest-derive = "0.3.0"

[dependencies]
rayon = "1.7.0"
